language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: tiddlywiki ./*wiki --build

after_success:
  - bash chmod ugo+x ./publish.sh
  - bash ./publish.sh

branches:
  only:
    - main